-- MySQL Script generated by MySQL Workbench
-- Wed Oct 11 12:44:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Censo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Censo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Censo` (
  `id_censo_anio` INT NOT NULL,
  PRIMARY KEY (`id_censo_anio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `id_departamento` VARCHAR(3) NOT NULL,
  `nombre_departamento` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tematica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tematica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tematica` (
  `id_tematica` CHAR NOT NULL,
  `tematica_descripcion` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_tematica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cuadro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cuadro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cuadro` (
  `id_cuadro` INT NOT NULL,
  `id_tematica` CHAR NOT NULL,
  `cuadro_titulo` VARCHAR(255) NOT NULL,
  `url_cuadro` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_cuadro`, `id_tematica`),
  INDEX `id_tematica_idx` (`id_tematica` ASC) VISIBLE,
  CONSTRAINT `id_tematica`
    FOREIGN KEY (`id_tematica`)
    REFERENCES `mydb`.`Tematica` (`id_tematica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tematica_has_Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tematica_has_Departamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tematica_has_Departamento` (
  `Tematica_id_tematica` CHAR NOT NULL,
  `Departamento_id_departamento` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`Tematica_id_tematica`, `Departamento_id_departamento`),
  INDEX `fk_Tematica_has_Departamento_Departamento1_idx` (`Departamento_id_departamento` ASC) VISIBLE,
  INDEX `fk_Tematica_has_Departamento_Tematica_idx` (`Tematica_id_tematica` ASC) VISIBLE,
  CONSTRAINT `fk_Tematica_has_Departamento_Tematica`
    FOREIGN KEY (`Tematica_id_tematica`)
    REFERENCES `mydb`.`Tematica` (`id_tematica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tematica_has_Departamento_Departamento1`
    FOREIGN KEY (`Departamento_id_departamento`)
    REFERENCES `mydb`.`Departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Censo_has_Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Censo_has_Departamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Censo_has_Departamento` (
  `Censo_id_censo` INT NOT NULL,
  `Departamento_id_departamento` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`Censo_id_censo`, `Departamento_id_departamento`),
  INDEX `fk_Censo_has_Departamento_Departamento1_idx` (`Departamento_id_departamento` ASC) VISIBLE,
  INDEX `fk_Censo_has_Departamento_Censo1_idx` (`Censo_id_censo` ASC) VISIBLE,
  CONSTRAINT `fk_Censo_has_Departamento_Censo1`
    FOREIGN KEY (`Censo_id_censo`)
    REFERENCES `mydb`.`Censo` (`id_censo_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Censo_has_Departamento_Departamento1`
    FOREIGN KEY (`Departamento_id_departamento`)
    REFERENCES `mydb`.`Departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
